# Generated by Django 4.1.6 on 2023-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_screen_viewing_delete_filmshowings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
