# Generated by Django 4.1.6 on 2023-04-27 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_film_rating_alter_film_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticketid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ticket_quantity', models.PositiveIntegerField()),
                ('film_title', models.CharField(max_length=100)),
                ('film_duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='club',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.representative'),
        ),
    ]
