# Generated by Django 4.1.6 on 2023-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_create_cinema_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmshowings',
            name='screen',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
