# Generated by Django 4.1.6 on 2023-05-08 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
