# Generated by Django 4.1.6 on 2023-05-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alter_club_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
        migrations.DeleteModel(
            name='CinemaManager',
        ),
    ]
