# Generated by Django 4.1.6 on 2023-05-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_remove_cinemamanager_user_delete_accountmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
