version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: project
      MYSQL_TCP_PORT: 3000
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose: 
      - 3000
    ports:
      - 3000:3000
    # Persistant Storage
    volumes:  
      - ./db:/var/lib/mysql
    # Healthcheck - Wait for the database to be ready
    healthcheck: 
      test: ["CMD", "mysql" , "-u", "root", "-proot", "-e", "USE project"]
      interval: 10s
      timeout: 2s
      retries: 30
  # django:
  #   container_name: django
  #   build: .
  #   command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Run Django and migrate
  #   volumes:
  #     - .:/web
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     db:
  #       condition: service_healthy